name = "i-score"
main = "src/worker.ts"
compatibility_date = "2025-10-08"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = "out"
binding = "ASSETS"

[observability]
enabled = true

# D1データベースの設定
[[d1_databases]]
binding = "DB"
database_name = "i-score-db"
database_id = "fdcb7241-930e-4ef5-97d2-08f6358faff4"
migrations_dir = "drizzle"

# 環境変数の設定
[vars]
BETTER_AUTH_URL = "https://i-score.insomnia-scorer.workers.dev"
NEXT_PUBLIC_BETTER_AUTH_URL = "https://i-score.insomnia-scorer.workers.dev"
GOOGLE_CLIENT_ID = "792942722187-rs65cnd38a9nkncqvo0is3uk80r6118l.apps.googleusercontent.com"
LINE_CLIENT_ID = "2009221282"
